<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net10.0-windows</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>disable</ImplicitUsings>
		<UseWPF>true</UseWPF>
		<UseWindowsForms>true</UseWindowsForms>

		<!-- Sets the icon for the compiled .exe file -->
		<ApplicationIcon>app.ico</ApplicationIcon>
	</PropertyGroup>

	<ItemGroup>
		<!-- Embeds the icon as a resource -->
		<Resource Include="app.ico" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="NDILibDotNetAdvanced" Version="*" />
	</ItemGroup>

</Project>